# This is a basic workflow to build robot code.

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches-ignore: [ main ]

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Set safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run tests on robot code
      run: ./gradlew build

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.7.0
      with:
        versionSpec: 6.8.x
    
    - name: Determine Version
      id: version_step
      uses: gittools/actions/gitversion/execute@v4.7.0

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ env.fullSemVer }}
        prerelease: true
